# GitHub action to build LAMMPS on Ubuntu
name: "build for Linux"

on: push

jobs:
  build:
    name: Build Linux
    # if: ${{ github.repository == 'lammps/lammps' }}
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        ref: mala

    - name: Install build-essential
      run: sudo apt install -y build-essential

    - name: Create Build Environment
      run: mkdir build
        
    - name: Building LAMMPS via CMake
      working-directory: build
      run: cmake ../cmake -D BUILD_SHARED_LIBS=yes -D PKG_ML-SNAP=yes 

    - name: build
      working-directory: build
      run: cmake --build -j4 .

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: liblammps
        path: build/liblammps.so.0

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Download a single artifact
        uses: actions/download-artifact@v4

      - name: Publish package
        run: |
          pwd
          ls -la liblammps
          ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
