# GitHub action to build LAMMPS on Ubuntu
name: "build for Linux"

on: push

jobs:
  build:
    name: Build Linux
    # if: ${{ github.repository == 'lammps/lammps' }}
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        ref: mala

    - name: Install build-essential
      run: sudo apt install -y build-essential

    - name: Create Build Environment
      run: ls -la

    - name: Create Build Environment
      run: |
        mkdir build
        cd build
        ls -la
        pwd
        
    - name: Building LAMMPS via CMake
      run: |
        pwd
        cmake ../cmake -D BUILD_SHARED_LIBS=yes -D PKG_ML-SNAP=yes 

    - name: build
      run: cmake --build .

    - name: show build content
      run: ls -la
